services:
  # --- APLICAÇÃO NEXT.JS (MODO DEV) ---
  app-upkids-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-nextjs-dev
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - HOST=0.0.0.0      # Garante que o Next escute em todas as interfaces
      - PORT=${APP_PORT}  # Garante que o Next use a porta do seu .env
    volumes:
      - .:/app            # Sincroniza o código local com o container
      - /app/node_modules # Protege os pacotes instalados no container
      - /app/.next        # Evita conflitos de build entre local e container
    command: npm run dev  # Comando para habilitar o Hot Reload
    depends_on:
      - app-upkids-db-dev # No modo dev, focar no banco de dev
    env_file:
      - .env

  # --- POSTGRESQL DE DESENVOLVIMENTO ---
  app-upkids-db-dev:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_DEV_USER}
      - POSTGRES_PASSWORD=${DB_DEV_PASSWORD}
      - POSTGRES_DB=${DB_DEV_NAME}
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    ports:
      - "${DB_DEV_PORT_EXTERNAL}:5432"

volumes:
  pg_dev_data:
    name: ${PROJECT_NAME}-dev-vol